markdown: rdiscount
permalink: /:title/
url: http://harvey-he.github.io
name: Harvey-He
author: harvey
qq: 475147731
email: harvey-he@qq.com
duoshuo: harvey-he
beian: 
cnzz: 
weibo: 1735199545
github: harvey-he
pygments: true
safe: true
paginate: 20
about: "这里是 harvey-he 的个人博客"
